import { createContext, useContext, useState } from 'react';

const translations = {
    en: {
        appName: 'Clean Madurai',
        appSubtitle: 'Smart Waste Management',
        dashboard: 'Dashboard',
        dustbinMap: 'Dustbin Map',
        complaints: 'Complaints',
        workers: 'Workers',
        areaIncharge: 'Area Incharge',
        reportIssue: 'Report Issue',
        chatbot: 'Recycle Bot',
        totalDustbins: 'Total Dustbins',
        activeComplaints: 'Active Complaints',
        workersOnDuty: 'Workers On Duty',
        resolvedToday: 'Resolved Today',
        search: 'Search areas, workers...',
        mapTitle: 'Madurai Dustbin Locations',
        mapLegendClean: 'Clean',
        mapLegendFull: 'Full (Complaint)',
        mapLegendPartial: 'Partially Full',
        complaintsTitle: 'Recent Complaints',
        all: 'All',
        pending: 'Pending',
        inProgress: 'In Progress',
        resolved: 'Resolved',
        area: 'Area',
        status: 'Status',
        reportedAt: 'Reported At',
        dustbinId: 'Dustbin ID',
        workerTitle: 'Cleanliness Workers',
        uploadPhoto: 'Upload Geo-Tagged Photo',
        uploadHint: 'Take a photo after cleaning the dustbin',
        mandatory: '* Mandatory daily upload',
        location: 'Location',
        lastUpdate: 'Last Update',
        inchargeTitle: 'Area Incharge Officers',
        totalBins: 'Total Bins',
        pendingLabel: 'Pending',
        resolvedLabel: 'Resolved',
        reportTitle: 'Report a Complaint',
        selectArea: 'Select Area',
        description: 'Description',
        descPlaceholder: 'Describe the issue with the dustbin...',
        submit: 'Submit Complaint',
        chatWelcome: 'Hi! I\'m your Recycle Bot 🌿 Ask me anything about recycling, waste management, or eco-friendly practices!',
        chatPlaceholder: 'Ask about recycling...',
        english: 'English',
        tamil: 'தமிழ்',
        login: 'Login',
        loginSubtitle: 'Sign in to manage cleanliness',
        username: 'Username',
        password: 'Password',
        selectRole: 'Select your role',
        admin: 'Admin',
        worker: 'Worker',
        citizen: 'Citizen',
        logout: 'Logout',
        notifications: 'Notifications',
        assignedArea: 'Assigned Area',
        phone: 'Phone',
    },
    ta: {
        appName: 'சுத்தமான மதுரை',
        appSubtitle: 'ஸ்மார்ட் கழிவு மேலாண்மை',
        dashboard: 'டாஷ்போர்டு',
        dustbinMap: 'குப்பைத்தொட்டி வரைபடம்',
        complaints: 'புகார்கள்',
        workers: 'தொழிலாளர்கள்',
        areaIncharge: 'பகுதி பொறுப்பாளர்',
        reportIssue: 'புகார் அளிக்கவும்',
        chatbot: 'மறுசுழற்சி போட்',
        totalDustbins: 'மொத்த குப்பைத்தொட்டிகள்',
        activeComplaints: 'செயலில் உள்ள புகார்கள்',
        workersOnDuty: 'பணியில் உள்ள தொழிலாளர்கள்',
        resolvedToday: 'இன்று தீர்க்கப்பட்டவை',
        search: 'பகுதிகள், தொழிலாளர்கள் தேடுங்கள்...',
        mapTitle: 'மதுரை குப்பைத்தொட்டி இடங்கள்',
        mapLegendClean: 'சுத்தமான',
        mapLegendFull: 'நிரம்பிய (புகார்)',
        mapLegendPartial: 'பகுதி நிரம்பிய',
        complaintsTitle: 'சமீபத்திய புகார்கள்',
        all: 'அனைத்தும்',
        pending: 'நிலுவையில்',
        inProgress: 'செயல்பாட்டில்',
        resolved: 'தீர்க்கப்பட்டது',
        area: 'பகுதி',
        status: 'நிலை',
        reportedAt: 'புகார் நேரம்',
        dustbinId: 'தொட்டி எண்',
        workerTitle: 'சுத்தம் தொழிலாளர்கள்',
        uploadPhoto: 'புவி-குறி புகைப்படம் பதிவேற்றவும்',
        uploadHint: 'குப்பைத்தொட்டியை சுத்தம் செய்த பின் புகைப்படம் எடுக்கவும்',
        mandatory: '* கட்டாய தினசரி பதிவேற்றம்',
        location: 'இடம்',
        lastUpdate: 'கடைசி புதுப்பிப்பு',
        inchargeTitle: 'பகுதி பொறுப்பாளர் அதிகாரிகள்',
        totalBins: 'மொத்த தொட்டிகள்',
        pendingLabel: 'நிலுவை',
        resolvedLabel: 'தீர்வு',
        reportTitle: 'புகார் அளிக்கவும்',
        selectArea: 'பகுதியை தேர்ந்தெடுக்கவும்',
        description: 'விவரம்',
        descPlaceholder: 'குப்பைத்தொட்டியின் பிரச்சனையை விவரிக்கவும்...',
        submit: 'புகார் சமர்ப்பிக்கவும்',
        chatWelcome: 'வணக்கம்! நான் உங்கள் மறுசுழற்சி போட் 🌿 மறுசுழற்சி, கழிவு மேலாண்மை பற்றி கேளுங்கள்!',
        chatPlaceholder: 'மறுசுழற்சி பற்றி கேளுங்கள்...',
        english: 'English',
        tamil: 'தமிழ்',
        login: 'உள்நுழைக',
        loginSubtitle: 'சுத்தத்தை நிர்வகிக்க உள்நுழையவும்',
        username: 'பயனர்பெயர்',
        password: 'கடவுச்சொல்',
        selectRole: 'உங்கள் பங்கை தேர்ந்தெடுக்கவும்',
        admin: 'நிர்வாகி',
        worker: 'தொழிலாளர்',
        citizen: 'குடிமகன்',
        logout: 'வெளியேறு',
        notifications: 'அறிவிப்புகள்',
        assignedArea: 'ஒதுக்கப்பட்ட பகுதி',
        phone: 'தொலைபேசி',
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('en');

    const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

    const toggleLang = (newLang) => setLang(newLang);

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
